In [15]:
import numpy as np

# check how numpy.dot() works
a = np.array([[2,1,5],[3,1,1], [4,5,1]])
b = np.array([[1],[2],[3]])
print(a)
print(b)
print(np.shape(a))
print(np.shape(b))

[[2 1 5]
 [3 1 1]
 [4 5 1]]
[[1]
 [2]
 [3]]
(3, 3)
(3, 1)


In [13]:
c = a.T.dot(b)
print(c)

[[8]
 [3]]


In [16]:
d = a*b
print(d)

[[ 2  1  5]
 [ 6  2  2]
 [12 15  3]]


AttributeError: 'numpy.ndarray' object has no attribute 'type'