In [27]:
import numpy as np

A = np.zeros((4,4))
A[0,:] = 1
A[1,:] = 5
A[2,:] = 3
A[3,:] = 10
A[:,1] = 2*A[:,1]
A[:,2] = A[:,0] + 3*A[:,1]
A[:,3] = 5*A[:,0]
print(A)
print(A.T)


[[ 1.  2.  7.  5.]
 [ 5. 10. 35. 25.]
 [ 3.  6. 21. 15.]
 [10. 20. 70. 50.]]
[[ 1.  5.  3. 10.]
 [ 2. 10.  6. 20.]
 [ 7. 35. 21. 70.]
 [ 5. 25. 15. 50.]]


In [19]:
b = np.ones(4)
b[1] = 2
b[2] = 3
b[3] = 4
print(b)
b= np.reshape(b,)

[1. 2. 3. 4.]


In [26]:
print((A.T*b).T)

[[  1.   2.   7.   5.]
 [ 10.  20.  70.  50.]
 [  9.  18.  63.  45.]
 [ 40.  80. 280. 200.]]
